### PR TITLE
Add option to install settings for ep_ldapauth plugin

### PR DESCRIPTION
**Pull request by sergiik**
Signed-off-by: Sergii Kipot <kipot.sergey@gmail.com>

### CODE REVIEW

**Comment by bastelfreak** [comment]
thanks for the PR @sergiik! Are you able to add spec tests for it?

**Comment by mattock** [comment]
This would be good to have. Right now I have a local hack that enables LDAP authentication in Etherpad.

**Comment by sergiik** [comment]
Ok. I will add spec tests

**Comment by sergiik** [comment]
Tests have have been added

**Comment by bastelfreak** [comment]
thanks!

**Pull request merged**
