### PR TITLE
Fixes to upstart init script and documentation

### PR DESCRIPTION
**Pull request by mattock**
Right now the upstart file gets rejected because of a syntax error, at least on Ubuntu 14.04. For details refer to http://upstart.ubuntu.com/cookbook/#chdir.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @mattock, thanks for the PR. Can you please squash and rebase after #15 got merged? This should fix the rubocop errors.

**Comment by mattock** [comment]
@bastelfreak : do you want all commits to be squashed into one?

**Comment by mattock** [comment]
@bastelfreak : ping ^^^

**Comment by mattock** [comment]
@bastelfreak the PR is now based on latest upstream code.

**Comment by bastelfreak** [comment]
thanks @mattock! sorry that I missed your last ping.

**Comment by mattock** [comment]
@bastelfreak thanks for merging!

**Pull request merged**
