### PR TITLE
Modulesync

### PR DESCRIPTION
**Pull request by dhoppe**
I need someone who is able to create credentials for `.travis.yml`.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@dhoppe https://github.com/voxpupuli/plumbing/blob/master/share/travis_secrets#L22

**Comment by dhoppe** [comment]
@igalic I am not sure how [this](https://github.com/voxpupuli/puppet-etherpad/blob/075d8c952320d2dab888c7eacc8a569bfcd0bb62/manifests/init.pp#L13) is supposed to work. If the fact is unknown, this will result with an error message like:  ```Unknown variable: '::service_provider'```

**Comment by jyaworski** [comment]
This is a puppet 4 module, and we're testing against Puppet 3. We need some way to let modulesync know we don't want the Puppet 3 checks @bastelfreak

**Comment by bastelfreak** [comment]
well shit /o\

**Pull request closed without merging**
